services:
  - type: web
    name: nilaya-hospital-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 3001
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        sync: false
      - key: NEON_DATABASE_URL
        sync: false
      - key: BREVO_API_KEY
        sync: false
      - key: BREVO_SENDER_EMAIL
        sync: false
      - key: BREVO_SENDER_NAME
        value: "Nilaya Hospital"
      - key: BREVO_RECEIVER_EMAIL
        sync: false
